# Generated by Django 4.0.6 on 2022-07-25 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtivosMonitorados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ativo', models.TextField(max_length=15)),
                ('tunel_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tunel_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodicidade', models.IntegerField(verbose_name='Período de att em horas')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoPrecos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ativo', models.TextField(max_length=15)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_att', models.DateTimeField(verbose_name='Data de atualização')),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvestimentoApp.ativosmonitorados')),
            ],
        ),
    ]
