# Generated by Django 4.0.6 on 2022-07-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestimentoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativosmonitorados',
            name='codigo_ativo',
            field=models.TextField(max_length=15, unique=True),
        ),
    ]
